name: archlinux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  archlinux:

    runs-on: ubuntu-latest

    container: archlinux

    steps:
      - run: pacman -Syyuu --noconfirm
      - run: pacman -S     --noconfirm git cmake ninja gcc

      - uses: actions/checkout@main

      - run:  cmake --version
      - run:  cmake -S . -B   build.d -G Ninja -DCMAKE_INSTALL_PREFIX=./output -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE=Debug
      - run:  cmake --build   build.d
      - run:  cmake --install build.d


      - run:  ./output/bin/sysinfo --help
      - run:  ./output/bin/sysinfo --version

      - run:  ./output/bin/sysinfo -h
      - run:  ./output/bin/sysinfo -v

      - run:  ./output/bin/sysinfo kind
      - run:  ./output/bin/sysinfo type
      - run:  ./output/bin/sysinfo code
      - run:  ./output/bin/sysinfo name
      - run:  ./output/bin/sysinfo vers
      - run:  ./output/bin/sysinfo arch
      - run:  ./output/bin/sysinfo ncpu
      - run:  ./output/bin/sysinfo libc

      - run:  ./output/bin/sysinfo
