name: gentoo

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  gentoo:
    runs-on: ubuntu-latest

    container: madhacking/gentoo

    steps:
      - run:  emerge cmake dev-util/ninja gcc

      - uses: actions/checkout@v4

      - run:  cmake -S . -B   build.d -G Ninja -DCMAKE_INSTALL_PREFIX=./output -DCMAKE_VERBOSE_MAKEFILE=ON
      - run:  cmake --build   build.d
      - run:  cmake --install build.d

      - run:  ./output/bin/sysinfo --help
      - run:  ./output/bin/sysinfo --version

      - run:  ./output/bin/sysinfo -h
      - run:  ./output/bin/sysinfo -v

      - run:  ./output/bin/sysinfo kind
      - run:  ./output/bin/sysinfo type
      - run:  ./output/bin/sysinfo code
      - run:  ./output/bin/sysinfo name
      - run:  ./output/bin/sysinfo vers
      - run:  ./output/bin/sysinfo arch
      - run:  ./output/bin/sysinfo ncpu
      - run:  ./output/bin/sysinfo libc

      - run:  ./output/bin/sysinfo
